API_ID: 16596628
API_HASH: 421764a823ee2dff786d413aea09959f
BOT_TOKEN: 5713549903:AAHBevkxw4XMhdAPUqvQDjS77ENHH5uk4DA


MONGO_URL: mongodb+srv://vs:tUYncTxdXiaPhMbi@cluster0.3b1bnas.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13757.c273.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 13757
REDIS_PASS: hdD4WujQwT8ouE5BD7LVUFuanC0LyBBa

SESSION_API_ID: 16596628
SESSION_API_HASH: 421764a823ee2dff786d413aea09959f
SESSION_STRING: 1ApWapzMBu4QdxVqi69TjhSgndSJog34C7DHuNSdbiu1KrUmGnE4o637ZY_qPF3v6USd8DNcE7FWCZoN34YkJpFb6dQ3V9ZZmvp5Es1G7d6p00HJPf3UvEMl9MBUfC2Jeg7eNBsnZ9zsJc9_MLoiNdKRpEchj5R8p0_o1kbZ5Hp710e5wyvGMB8WLLOZ6BkGQ8DiZCGrXE17PNgC-x56QIwPrFIlpoivrRXF1FiICqrkUjBRLCY3VPE0Q-OcImFsLx8D3dCAgQ7Vw6hjOUvtogBDqQT5La7k5m6Vf_NCIYj_1RVbtoWtKI_z--r6HKuaqhSvVZN8XKWTdQl86-3Ub5RkHyxXPvHQ=

ADMINS: 5136746907

OWNER: 5383908433
OWNER: 5136746907

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT:  
# LOG_CHAT: -1001657108198
LOG_CHAT: -1001761930779



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

