API_ID: 16596628
API_HASH: 421764a823ee2dff786d413aea09959f
BOT_TOKEN: 5713549903:AAHBevkxw4XMhdAPUqvQDjS77ENHH5uk4DA


MONGO_URL: mongodb+srv://vs:tUYncTxdXiaPhMbi@cluster0.3b1bnas.mongodb.net/?retryWrites=true&w=majority
REDIS_URI:redis-13757.c273.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT:13757
REDIS_PASS:hdD4WujQwT8ouE5BD7LVUFuanC0LyBBa

SESSION_API_ID: 15649932
SESSION_API_HASH: ac748828574bf5b0ff75eef790d902df
SESSION_STRING: BQA0x19qEbt533Aiu0y4cgfMJNM7ZQIiOQFET3RmJMtpWpM8DPDpdqY3TCJTPSfguTa0h7pc5_MVBrW_ULbmQZC_CFoX9Gquuh7a7hhJKVyrXM6FTsMt7JbHPXmBQl5R9WN-mr0fHiGrW07eiHTemwc92fAwpkZIUhVjBVqZNECGxee_VALRwSK6EA2lEN8po35h0ngWjL9GHlQlzmup6MfAhkY9seQVFeKdMkyBZ0_pWj-JWenF0oNcbBG8cosZtt1WJCbRPFK45VZKNAJF-qE05aq7eZchbMKmpiOank7pyB-nKAsplfoxhqv5-exqDpaMFDZSOrdMt1wHebbZ0VvaAAAAAUJ-Y0YA

ADMINS: 5136746907

OWNER: 5383908433
OWNER: 5136746907

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT:  
# LOG_CHAT: -1001657108198
LOG_CHAT: -1001761930779



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

