API_ID: 16596628
API_HASH: 421764a823ee2dff786d413aea09959f
BOT_TOKEN: 5459435179:AAHZe8yOLcVDclL73GSJv-yh-Gn6ujAvsro


MONGO_URL: mongodb+srv://vs:tUYncTxdXiaPhMbi@cluster0.3b1bnas.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-13757.c273.us-east-1-2.ec2.cloud.redislabs.com
REDIS_PORT: 13757
REDIS_PASS: hdD4WujQwT8ouE5BD7LVUFuanC0LyBBa

SESSION_API_ID: 16596628
SESSION_API_HASH: 421764a823ee2dff786d413aea09959f
SESSION_STRING: AgBeWwXqqguQg1EG5IcpXCnAmtyRSFvYApEhARwG2EAv_ZkT_IEH4IE-LsQT0-Bie-tGBrzvL0dOSm3P_kOPmbbz0tuGcrzn7KkK6J_AxhTXYaWvjIww5IMMDKANoBxMPODFLaWpofTz__Pk5nbWY-XbnLQxwrMZaHPn0CoFGUtLRKnqkHYlsoBUoHX-H5I22j2B8svlH5bzSildP1Hu4gEdbKsSau-H0E02cJLKbcLt7Wy15D1ZPb6ivbX8O4wzKP1bcb-YkpUkzscPXohHbAvH2IWqq3i996ycQeHBdQ5rc-q1Rf-u_n8pBg0OZuq4_O_JpkFsRU8QDdFGwyoET5ReAAAAATIsiZsA

ADMINS: 
  - 5136746907

OWNER: 5136746907

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: xteamBDChat
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

